---
format: html
editor: visual
---


ggplot2 extenders meets in virtually every few months.  Presenters discuss motivation, origins, and challenges of their extension projects!  

Interested in joining us? Please drop a note [here](https://github.com/teunbrand/ggplot-extension-club/discussions/35) so we can be in touch.



Upcoming meeting:

- [{animint2}](https://github.com/animint/animint2), Toby Hocking, August 19, 2024

Past meetings

- [{ggnewscale}](https://eliocamp.github.io/ggnewscale/), Elio Campitelli, June 22/23, 2024
- [{ggedit}](https://yonicd.github.io/ggedit/), Jonathan Sidi, May 11, 2024
- A conversation with Di Cook, early extension and [{GGally}](https://ggobi.github.io/ggally/), March 12/13, 2024
- [{ggdag}](https://r-causal.github.io/ggdag/), Malcolm Barrett, Feb 10, 2024
- [{ggflowchart}](https://nrennie.rbind.io/ggflowchart/) Nicola Rennie & [{arrowheadr}](https://wjschne.github.io/arrowheadr/) W. Joel Schneider  Nov 4, 2023
- [{ggeasy}](https://jonocarroll.github.io/ggeasy/) Jonathan Carroll, Sept 2, 2023
- [{ggsurvfit}](https://www.danieldsjoberg.com/ggsurvfit/), Daniel Sjoberg, June 10, 2023
- [{ggcirclepack}](https://github.com/EvaMaeRey/ggcirclepack), Gina Reynolds, April 15, 2023
- [*Fundamentals of Data Visualization*](), Claus Wilke, Jan 28, 2022

- {ggtrace}, June Choe, July 16, 2022
- {ggh4x}, Teun Van Den Brand, June 11, 2022 
- {geomtextpath} Allan Cameron May 7, 2022
- {ggbump} David Sjoberg, April 9, 2022
- First meeting, March 19, 2022
